# this file is used to define the environment Docker should use to run your app
#Use an official lightweight Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all project files into the container
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose ports: FastAPI (8000), Streamlit (8501)
EXPOSE 8000
EXPOSE 8501

# Set the default command (you can override during runtime)
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

# | Option             | Meaning                                                    |
# | ------------------ | ---------------------------------------------------------- |
# | `-p 8501:8501`     | Maps host's port 8501 to container's port 8501 (Streamlit) |
# | `-p 8000:8000`     | Maps host's port 8000 to container's port 8000 (FastAPI)   |
# | `--name`           | Gives the container a name (`employee-tracker-container`)  |
# | `employee-tracker` | The image name you built                                   |

# docker run -p 8501:8501 -p 8000:8000 --name employee-tracker-container employee-tracker














# FROM python:3.11-slim: Base image with Python 3.11.
# WORKDIR /app: Sets /app as the working directory.
# COPY . .: Copies all files from your local machine into the container.
# RUN pip install...: Installs all required packages.
# EXPOSE: Declares which ports will be used.
# CMD: Tells Docker what to run by default (FastAPI server in this case).
